### PR TITLE
Write integration tests using envTest for NATS-manager controller

### PR DESCRIPTION
**Pull request by mfaizanse**
**Description**

Changes proposed in this pull request:

- Write integration tests using envTest for NATS-manager controller.
- Updated `resources/nats/templates/configmap.yaml` because some values were appearing on new line, and some values needed to be in quotes.

**Related issue(s)**

- https://github.com/kyma-project/nats-manager/issues/22

### CODE REVIEW

**Comment by mfaizanse** [comment]
pull-nats-manager-unit-test

**Review by friedrichwilken — APPROVED** [review]

**Pull request merged**
